
resources:
  - name: vijay_test_gitrepo_a
    type: GitRepo
    configuration:
      path: vijayreddy1991/runtime
      gitProvider: vijay
      branches:
        include: '^{{gitBranch}}$'
  - name: vijay_test_gitrepo_b
    type: GitRepo
    configuration:
      path: vijayreddy1991/runtime
      gitProvider: vijay
      branches:
        include: test
      files:
        include: ^b\/.*$
        
        
  - name: vijay_test_gitrepo_c
    type: GitRepo
    configuration:
      path: vijayreddy1991/runtime
      gitProvider: vijay
      branches:
        include: test
      files:
        include: batch    
      buildOn:  # optional
        commit: true
pipelines:
  - name: vijay_custom_test
    steps:
      - name: build_a
        type: Bash
        configuration:
          inputResources:
            - name: vijay_test_gitrepo_a
        execution:
          onExecute:
            - cd $res_vijay_test_gitrepo_a_resourcePath
            - echo "test" >> test.txt
            - cat test.txt
            - git rev-parse --short HEAD
      - name: build_b
        type: Bash
        configuration:
          inputSteps:
            - name: build_a
          inputResources:
            - name: vijay_test_gitrepo_c
              trigger: true            
  
        execution:
          onExecute:
            - cd $res_vijay_test_gitrepo_b_resourcePath
            - echo "test" >> test.txt
            - cat test.txt
            - git rev-parse --short HEAD
            - printenv | grep res_vijay_test_gitrepo_b
