
resources:
  - name: test_1234
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/runtime
      branches:     
        include: master            

pipelines:
  - name: pipelines_vijay
    steps:
      - name: S_Bash1
        type: Bash
        configuration: 
          inputResources:          
            - name: test_1234           
#             - name: git_repo1
        execution:
          onExecute:
            - echo "executing step..."
            - printenv  
#             - sleep 300

      - name: S_Bash2
        type: Bash
        configuration: 
          inputResources:          
            - name: test_1234
#           inputSteps:
#             - name: S_Bash1

        execution:
          onExecute:
            - echo "executing step..."
            - printenv    






