resources:
  - name: S_PS_R_FLSPEC_0018
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      aql: '{"items.find":{"name":{"$match":"s_foo*"}}}'
      target: 'C:\Users\pipelines\Desktop\'
      
  - name: S_PS_R_FLSPEC_0019
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      pattern: "*/s_foo*"
      limit: 1
      sortBy:
        - created
      target: 'C:\Users\pipelines\Desktop\'  
      
  - name: S_PS_R_FLSPEC_0020
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      pattern: "*/s_foo*"
      limit: 1
      excludePatterns:
        - "*/pipeInfo.json"
      target: 'C:\Users\pipelines\Desktop\'   
      
  - name: S_PS_R_FLSPEC_0021
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      pattern: "*/s_foo*"
      limit: 1
      exclusions:
        - "*/pipeInfo.json"
      target: 'C:\Users\pipelines\Desktop\'      
      
pipelines:
  - name: pipelines_S_PS_R_FLSPEC_0018
    steps:
      - name: S_PS_R_FLSPEC_0018
        type: PowerShell
        configuration:
          nodePool: win_2019
          inputResources:
            - name: S_PS_R_FLSPEC_0018
        execution:
          onExecute:
            - write-output "executing step..."
            - if (Test-Path "C:\Users\pipelines\Desktop\fileSpecPowerShell\s_foo"){ Write-Output "found the file" }
            - if (!(Test-Path "C:\Users\pipelines\Desktop\fileSpecPowerShell\s_foo")){ Write-Error "error finding the file" -ErrorAction Stop }
            
            

  - name: pipelines_S_PS_R_FLSPEC_0019
    steps:
      - name: S_PS_R_FLSPEC_0019
        type: PowerShell
        configuration:
          nodePool: win_2019
          inputResources:
            - name: S_PS_R_FLSPEC_0019
        execution:
          onExecute:
            - write-output "executing step..."
            - if (Test-Path "C:\Users\pipelines\Desktop\fileSpecPowerShell\s_foo"){ Write-Output "found the file" }
            - if (!(Test-Path "C:\Users\pipelines\Desktop\fileSpecPowerShell\s_foo")){ Write-Error "error finding the file" -ErrorAction Stop }   
            


  - name: pipelines_S_PS_R_FLSPEC_0020
    steps:
      - name: S_PS_R_FLSPEC_0020
        type: PowerShell
        configuration:
          nodePool: win_2019
          inputResources:
            - name: S_PS_R_FLSPEC_0020
        execution:
          onExecute:
            - write-output "executing step..."
            - if (Test-Path "C:\Users\pipelines\Desktop\fileSpecPowerShell\s_foo"){ Write-Output "found the file" }
            - if (Test-Path "C:\Users\pipelines\Desktop\fileSpecPowerShell\pipeInfo.json"){ Write-Error "found the wrong file" -ErrorAction Stop }
            - if (!(Test-Path "C:\Users\pipelines\Desktop\fileSpecPowerShell\s_foo")){ Write-Error "error finding the file" -ErrorAction Stop }   
            
            

  - name: pipelines_S_PS_R_FLSPEC_0021
    steps:
      - name: S_PS_R_FLSPEC_0021
        type: PowerShell
        configuration:
          nodePool: win_2019
          inputResources:
            - name: S_PS_R_FLSPEC_0021
        execution:
          onExecute:
            - write-output "executing step..."
            - if (Test-Path "C:\Users\pipelines\Desktop\fileSpecPowerShell\s_foo"){ Write-Output "found the file" }
            - if (Test-Path "C:\Users\pipelines\Desktop\fileSpecPowerShell\pipeInfo.json"){ Write-Error "found the wrong file" -ErrorAction Stop }
            - if (!(Test-Path "C:\Users\pipelines\Desktop\fileSpecPowerShell\s_foo")){ Write-Error "error finding the file" -ErrorAction Stop }            
            
